notifications:
  email: false

sudo: false

language: node_js
node_js: node

cache:
  directories:
    - node_modules
    - sysconfcpus

os:
  - linux

env:
  global:
    - ELM_VERSION="0.19.0-bugfix2"
    - ELM_TEST_VERSION="0.19.0-beta9"
    - SYSCONFCPUS="${TRAVIS_BUILD_DIR}/sysconfcpus/bin/sysconfcpus -n 2"
    - ELM_MAKE="${TRAVIS_BUILD_DIR}/node_modules/.bin/elm make"
    - ELM_TEST="node ${TRAVIS_BUILD_DIR}/node_modules/elm-test/bin/elm-test --compiler ${ELM_MAKE}"

install:
  - |
    [ $(node -p "require('elm/package.json').version") == $ELM_VERSION ] || npm install elm@$ELM_VERSION
  - |
    [ $(node -p "require('elm-test/package.json').version") == $ELM_TEST_VERSION ] || npm install elm-test@$ELM_TEST_VERSION
  - |
    [ $(node -p "require('uglify-js/package.json').version") ] || npm install uglify-js
  # Faster compile on Travis.
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

script:
  - $SYSCONFCPUS $ELM_TEST tests/CLI.elm

after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST == false ];
    then
      bash ./demo/deploy.sh;
    fi
  